Repository wangq131/4G06CapstoneProjectT5, pull requests merged in 2023-11, with the labels that each got.

#126 14 - Add lint check inside main workflow
  .github/workflows/main.yml
Labels: repo management

#131 128 VnV plan documentation (section 1 and section 3)
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#140 128-Finished the Appendix part for vNv
  .gitattributes
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#136 135-update SRS according to HA
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#133 134 - Add test cases for functional requirements
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation, deliverables

#141 128-VnV-final version
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#144 Fix VnV version error
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: bug, documentation

#162 161 - Clean priority raw data
  src/poc-data/README.md
  src/poc-data/__init__.py
  src/poc-data/clean-priority-data/clean-priority-data-with-analysis-steps.ipynb
  src/poc-data/clean-priority-data/task_priority_data_cleaned.csv
  src/poc-data/generate_mock_data.py
  src/poc-data/mock_data_poc.csv
  src/poc-data/upload_mock_data_to_s3.py
Labels: PoC, data cleaning

#167 155 - Add raw data csv file for priority model
  src/poc-data/task-priority-data/task_priority_data_raw.csv
Labels: data

#171 170 - Rename poc_data to poc-data
  src/README.md
  src/flask-app-instructions.md
  src/helper.py
Labels: bug

#172 124 - Add a training pipeline script to automate model training
  requirements.txt
  src/__init__.py
  src/config.py
  src/poc-data/task-priority-data/__init__.py
  src/poc-data/task-priority-data/clean_priority_raw_data_with_analysis_steps.ipynb
  src/poc-data/task-priority-data/preprocess_priority_cleaned_data_with_analysis_steps.ipynb
  src/task-priority-training-pipeline/README.md
  src/task-priority-training-pipeline/trained_priority_model.joblib
  src/task-priority-training-pipeline/training_pipeline.py
Labels: training pipeline

#173 124 - Add training pipeline workflow diagram
  src/__init__.py
  src/task-priority-training-pipeline/trained_priority_model.joblib
  src/task-priority-training-pipeline/training_pipeline.png
Labels: PoC, training pipeline

#174 124 - Replace y with less classes
  src/task-priority-training-pipeline/training_pipeline.py
Labels: bug

#177 118-first unit test
  test/README.md
  test/__init__.py
  test/test_app.py
Labels: flask app, unit tests

#176 157 modeltraining gaoq
  src/__init__.py
  src/task-priority-training-pipeline/trained_priority_model.joblib
  src/task-priority-training-pipeline/training_pipeline.py
  src/task-priority-training-pipeline/training_results.md
Labels: Model

#178 157 - Add the model training result - shis20
  src/task-priority-training-pipeline/training_pipeline.py
  src/task-priority-training-pipeline/training_results.md
Labels: Medium

#175 168 refine pdf upload and extraction
  requirements.txt
  src/__init__.py
  src/app.py
  src/poc-data/moc_course_info.csv
  src/templates/course_detail_page.html
  src/templates/course_page.html
Labels: flask app

#181 168-issue fixed
  src/app.py
  src/helper.py
  src/poc-data/mock_course_info.csv
Labels: bug

#159 156 UI Design gaoq20
  requirements.txt
  src/__init__.py
  src/app.py
  src/config.py
  src/poc-data/clean-priority-data/clean-priority-data-with-analysis-steps.ipynb
  src/poc-data/clean-priority-data/task_priority_data_cleaned.csv
  src/poc-data/mock_data_tasks.csv
  src/poc-data/upload_mock_data_to_s3.py
  src/static/task.css
  src/task-priority-training-pipeline/training_pipeline.py
  src/templates/index.html
Labels: flask app

#185 Revert "156 UI Design gaoq20"
  requirements.txt
  src/__init__.py
  src/app.py
  src/config.py
  src/poc-data/clean-priority-data/clean-priority-data-with-analysis-steps.ipynb
  src/poc-data/clean-priority-data/task_priority_data_cleaned.csv
  src/poc-data/mock_data_tasks.csv
  src/poc-data/upload_mock_data_to_s3.py
  src/static/task.css
  src/task-priority-training-pipeline/training_pipeline.py
  src/templates/index.html
Labels: bug

#180 179 - Integrate trained priority model to our website
  src/__init__.py
  src/app.py
  src/config.py
  src/flask-app-instructions.md
  src/helper.py
  src/poc-data/poc_task_priority_input.csv
  src/task-priority-training-pipeline/trained_priority_model.joblib
  src/task_priority_training_pipeline/README.md
  src/task_priority_training_pipeline/__init__.py
  src/task_priority_training_pipeline/trained_priority_model.joblib
  src/task_priority_training_pipeline/training_pipeline.png
  src/task_priority_training_pipeline/training_pipeline.py
  src/task_priority_training_pipeline/training_results.md
  src/templates/model_page.html
Labels: flask app, PoC, Model

#188 187 - Add model pages html
  src/app.py
  src/flask-app-instructions.md
  src/templates/model_page.html
  src/templates/model_prediction_page.html
Labels: flask app, UI, Model

#190 160 - Fixed the problem of header icon floating
  src/static/style.css
  src/templates/header.html
Labels: bug

#191 189-the POC markdown has been added
  docs/PoC/PoC_workflow.md
  src/app.py
  src/poc-data/mock_course_info.csv
  src/templates/course_detail_page.html
Labels: PoC

#184 118 - test for dowload, change username, add course
  test/test_app.py
Labels: flask app, unit tests

#194 193 - Fix import, add ChatGPT citation
  src/README.md
Labels: bug

#183 182 unit tests qinj15
  requirements.txt
  src/app.py
  src/helper.py
  test/README.md
  test/test_app.py
Labels: unit tests

#195 192- Revise the model UI
  src/app.py
  src/static/style.css
  src/templates/course_detail_page.html
  src/templates/course_page.html
  src/templates/header.html
  src/templates/model_page.html
  src/templates/model_prediction_page.html
  src/templates/plan_page.html
  src/templates/profile_page.html
Labels: Medium

#197 196-PoC has been updated
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/DevelopmentPlan/DevelopmentPlan.tex
Labels: documentation, PoC

#199 198 - Extract instructor name feature has been updated
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/DevelopmentPlan/DevelopmentPlan.tex
  src/app.py
  src/config.py
  src/helper.py
  src/poc-data/mock_course_info.csv
  src/templates/course_detail_page.html
Labels: flask app

#203 202-unit tests bugs have been fixed
  src/helper.py
  src/poc-data/mock_course_info.csv
  test/test_app.py
Labels: bug

#204 156 UI recovery
  src/app.py
  src/config.py
  src/poc-data/mock_data_tasks.csv
  src/poc-data/upload_mock_data_to_s3.py
  src/static/task.css
  src/task_priority_training_pipeline/tasks
  src/templates/index.html
Labels: flask app

#205 left aligh tasklists
  src/poc-data/mock_course_info.csv
  src/static/task.css
Labels: flask app
