Repository wangq131/4G06CapstoneProjectT5, pull requests merged in 2023-10, with the labels that each got.

#49 48 - Create lecture issue template
  .github/ISSUE_TEMPLATE/leture-issue-template.md
Labels: documentation, repo management, Lecture

#52 24-Development-Plan-Changes-after-review-from-Jingyao
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/DevelopmentPlan/DevelopmentPlan.tex
Labels: documentation, High

#46 24-Problem-Statement-from-Shuting
  docs/Common.tex
  docs/ProblemStatementAndGoals/ProblemStatement.pdf
  docs/ProblemStatementAndGoals/ProblemStatement.tex
Labels: documentation, High

#56 readme added
  .gitignore
  README.md
Labels: documentation

#69 68 - Add appendix section to SRS
  docs/SRS-Volere/SRS.tex
Labels: documentation

#73 70-SRS 7.1,20, 22, 23 section form Jingyao
  docs/SRS-Volere/DFD.png
  docs/SRS-Volere/SRS.tex
Labels: documentation

#74 38 - context diagram, use case diagram done
  docs/SRS-Volere/Context Diagram.drawio.png
  docs/SRS-Volere/SRS.tex
  docs/SRS-Volere/Use Case Diagram.drawio.png
Labels: documentation

#75 Revert "38 - context diagram, use case diagram done"
  docs/SRS-Volere/Context Diagram.drawio.png
  docs/SRS-Volere/SRS.tex
  docs/SRS-Volere/Use Case Diagram.drawio.png
Labels: bug

#76 Second PR
  docs/SRS-Volere/Context Diagram.drawio.png
  docs/SRS-Volere/SRS.tex
  docs/SRS-Volere/Use Case Diagram.drawio.png
Labels: documentation

#78 newest version srs
  docs/SRS-Volere/SRS.tex
Labels: documentation

#80 70-adding graph and symbols for costs section
  docs/SRS-Volere/SRS.tex
  docs/SRS/DFD.png
Labels: documentation

#81 64 Fix format issues
  docs/SRS-Volere/DFD.png
  docs/SRS-Volere/SRS.tex
  docs/SRS/Context Diagram.drawio.png
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
  docs/SRS/Use Case Diagram.drawio.png
Labels: documentation

#84 64 - Update pdf and fix small format
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#92 33 - Add pdflatex inside dev container configuration
  .devcontainer/devcontainer.json
Labels: repo management

#100 readme.md for srs done
  docs/SRS/README.md
Labels: documentation

#104 97 Hazard Analysis documentation from gao
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#105 97- HA section 5 & 6
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#115 108-Adding-Links-to-HA
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#117 114 - Set up a simple Flask app that can interact with S3
  .gitignore
  requirements.txt
  src/README.md
  src/app.py
  src/config.py
  src/flask-app-instructions.md
  src/poc_data/README.md
  src/poc_data/generate_mock_data.py
  src/poc_data/mock_data_poc.csv
  src/templates/index.html
Labels: flask app

#120 119 add basic function to change username
  src/app.py
  src/config.py
  src/helper.py
  src/poc_data/README.md
  src/poc_data/__init__.py
  src/poc_data/upload_mock_data_to_s3.py
  src/templates/index.html
Labels: flask app

#123 119 - Add more basic functions in flask web app
  src/app.py
  src/flask-app-instructions.md
  src/helper.py
  src/templates/index.html
Labels: flask app

#102 Changed the images size in SRS document for issue 85
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation
