Repository wangq131/4G06CapstoneProjectT5, pull requests merged in 2024-03, with the labels that each got.

#271 270-Change Vnv accordingly
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#273 VnVReport final version
  docs/VnVReport/Frequency of use of functions.png
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#274 bit change
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#292 289 view switch
  src/app.py
  src/instance/project.db
  src/static/js/taskDragDrop.js
  src/static/task.css
  src/templates/header.html
  src/templates/index.html
  src/templates/tasks.html
Labels: enhancement, flask app

#295 294 - Add API endpoint to get task details and integration between Pomodoro
  src/app.py
  src/instance/project.db
  src/static/js/pomodoro.js
  src/static/js/taskDragDrop.js
  src/templates/pomodoro_page.html
  src/templates/tasks.html
Labels: Medium, flask app

#291 287-get rid of sql
  src/app.py
  src/config.py
  src/helper.py
  src/instance/project.db
  src/poc-data/comment_data.csv
  src/poc-data/topic_data.csv
  src/static/style.css
  src/templates/add_topic_page.html
  src/templates/forum_page.html
  src/templates/forum_topic_page.html
  src/templates/search_forum_results.html
Labels: flask app, data cleaning, data

#300 298 improve feedback page
  src/app.py
  src/templates/feedback_page.html
Labels: Medium

#301 Revert "287-get rid of sql"
  src/app.py
  src/config.py
  src/helper.py
  src/instance/project.db
  src/poc-data/comment_data.csv
  src/poc-data/topic_data.csv
  src/static/style.css
  src/templates/add_topic_page.html
  src/templates/forum_page.html
  src/templates/forum_topic_page.html
  src/templates/search_forum_results.html
Labels: bug

#302 287 forum cs
  src/app.py
  src/config.py
  src/helper.py
  src/instance/project.db
  src/poc-data/comment_data.csv
  src/poc-data/topic_data.csv
  src/static/style.css
  src/templates/add_topic_page.html
  src/templates/forum_page.html
  src/templates/forum_topic_page.html
  src/templates/search_forum_results.html
Labels: bug, flask app, data cleaning

#305 303 - Update SRS after VnV
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
Labels: documentation

#304 299 calendar improve gaoq20
  src/static/task.css
  src/templates/tasks.html
Labels: flask app

#296 293-Improve-site-color-theme-and-UI
  src/static/style.css
  src/templates/course_detail_page.html
  src/templates/course_page.html
  src/templates/feedback_page.html
  src/templates/index.html
Labels: flask app

#306 293 improve site color theme and UI
  src/static/images/homepage_pic1.jpg
  src/static/images/logo.png
  src/static/style.css
  src/static/task.css
  src/templates/base.html
  src/templates/feedback_page.html
  src/templates/header.html
  src/templates/index.html
Labels: flask app

#309 Revert "293 improve site color theme and UI"
  src/static/images/homepage_pic1.jpg
  src/static/images/logo.png
  src/static/style.css
  src/static/task.css
  src/templates/base.html
  src/templates/feedback_page.html
  src/templates/header.html
  src/templates/index.html
Labels: bug

#310 Revert "293-Improve-site-color-theme-and-UI"
  src/static/style.css
  src/templates/course_detail_page.html
  src/templates/course_page.html
  src/templates/feedback_page.html
  src/templates/index.html
Labels: bug

#311 308 final change before demo
  src/app.py
  src/poc-data/extracted_course_works.csv
  src/poc-data/mock_course_info.csv
  src/static/images/home1.png
  src/static/images/home10.jpg
  src/static/images/home2.png
  src/static/images/home3.png
  src/static/images/home4.png
  src/static/images/home5.jpg
  src/static/images/home6.png
  src/static/images/home7.jpg
  src/static/images/home8.jpg
  src/static/images/home9.jpg
  src/static/images/logo.png
  src/static/style.css
  src/static/task.css
  src/templates/add_topic_page.html
  src/templates/base.html
  src/templates/course_detail_page.html
  src/templates/course_page.html
  src/templates/feedback_page.html
  src/templates/forum_page.html
  src/templates/header.html
  src/templates/index.html
  src/templates/pomodoro_page.html
Labels: bug

#319 319- Rename Course buddy to MacONE, update SRS
  docs/Common.tex
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftDetailedDes/MIS.tex
  docs/HazardAnalysis/HazardAnalysis.tex
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
  docs/VnVPlan/VnVPlan.tex
Labels: documentation
