Repository wangq131/4G06CapstoneProjectT5, pull requests merged in 2024-04, with the labels that each got.

#321 314 - the expo poster has been uploaded
  docs/Presentations/EXPO/EXPO Poster.pdf
  docs/Presentations/FinalPresentation/Final Demo Slides.pdf
Labels: documentation

#320 316-the bug has been fixed
  src/static/style.css
  src/templates/pomodoro_page.html
Labels: bug

#323 Update VnVPlan Document & Team Contribution
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/projMngmnt/Final_Team_Contrib.pdf
  docs/projMngmnt/Final_Team_Contrib.tex
Labels: documentation

#327 326 new tests since change
  src/UnitTest.md
  src/test_app.py
  test/README.md
  test/__init__.py
  test/test_app.py
Labels: unit tests

#326 324 Update the revised VnVReport
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation

#329 325 Update HA and Design Docs
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftArchitecture/UseHierachy.png
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#330 325 update project name
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
Labels: documentation

#331 322 files revise gaoq20
  LICENSE
  README.md
  docs/Reflection/Reflection.pdf
  docs/Reflection/Reflection.tex
Labels: documentation

#328 314 make module and comments
  src/app.py
  src/app_grid.py
  src/config.py
  src/course_page.py
  src/feedback_page.py
  src/forum_page.py
  src/helper.py
  src/poc-data/extracted_course_works.csv
  src/poc-data/mock_course_info.csv
  src/pomodoro_page.py
  src/profile_page.py
  src/static/js/appIcons.js
  src/static/js/pomodoro.js
  src/static/js/taskDragDrop.js
  src/task_priority_training_pipeline/training_pipeline.py
  src/tasks_page.py
  src/templates/add_topic_page.html
  src/templates/course_detail_page.html
  src/templates/course_page.html
  src/templates/feedback_page.html
  src/templates/forum_page.html
  src/templates/forum_topic_page.html
  src/templates/header.html
  src/templates/index.html
  src/templates/profile_page.html
  src/templates/search_forum_results.html
  src/templates/tasks.html
  src/util.py
Labels: flask app
